### ISSUE TITLE
Add Nashorn support.

### ISSUE THREAD

**Issue by jdalton** [jdalton/qunit-extras#14]
I've compiled [nashorn-1.8.0](http://lodash.com/_travis/nashorn-1.8.0.jar) but now need to tweak the `setTimeout` and `setInterval` shims to work with it.

**Comment by winterbe** [comment]
Looking forward to it! :+1:

**Comment by jdalton** [comment]
Basic supported added https://github.com/jdalton/qunit-extras/commit/3d19076bd50dbc9805ebe3b3beaeb0ddabcdb170. I still need to get the `setTimeout` and `setInterval` shims working better.

**Comment by jdalton** [comment]
Closing as `wontfix` after simplifying things and dropping support for Java environments.
