### ISSUE TITLE
Test failures with v1.4.2

### ISSUE THREAD

**Issue by orlitzky** [jdalton/qunit-extras#22]
I get the following attempting to run the test suite:

```bash
$ npm test

> qunit-extras@1.4.2 test /home/mjo/src/qunit-extras-1.4.2
> node test/test.js

----------------------------------------
qunit-extras
----------------------------------------
 FAIL - Some other test with a title
    FAIL | EQ | foo | Expected: 2, Actual: 1
----------------------------------------
    PASS: 7  FAIL: 1  TOTAL: 8
    Finished in 17 milliseconds.
----------------------------------------
npm ERR! Test failed.  See above for more details.
```

I also have a request that I'd like to tack on =)

In `test.js`, you load qunit via a relative path:

```javascript
load('../node_modules/qunitjs/qunit/qunit.js')
```

Would it be possible to replace that with a simple `require('qunitjs')`? The user may have qunit installed in his home directory or globally or somewhere else. Thank you!

**Comment by jdalton** [comment]
Hi @orlitzky! The test fails are by design at the moment. The QUnit past in test is intended for the dev dependency.

**Comment by orlitzky** [comment]
Oh, OK. I was hoping to use the tests to determine whether or not it's safe to install the package. I.e. if the test suite passes, it's OK, otherwise, we fail. (I'm packaging qunit-extras for Gentoo Linux).

For the dev dependency, I meant that the location `'../node_modules/qunitjs/qunit/qunit.js'` is only one potential location where you might find `qunit.js`. In my home directory, `'~/node_modules/qunitjs/qunit/qunit.js'` is equally valid. And so is the global `/usr/lib/node/qunitjs/qunit/qunit.js'`. If qunit is installed in any of those places, then it will consider the dev dependency met but the test suite will crash.

**Comment by jdalton** [comment]
Ah! Ok!
