### ISSUE TITLE
broken with latest QUnit, no longer works in shell

### ISSUE THREAD

**Issue by krisselden** [jdalton/qunit-extras#23]
The latest QUnit stopped exporting a global when it doesn't think it is in a browser, but if not in node it doesn't export anything.

**Comment by krisselden** [comment]
I can get it to run in node by making a context with QUnit like so https://github.com/stefanpenner/layout-bin-packer/blob/master/bin/test.js but I'm not sure I can get it to export QUnit with load in a shell without defining module.exports in a way that passes their UMD

**Comment by jdalton** [comment]
Yep.

**Comment by krisselden** [comment]
would a better issue have been the README.md example does not actually work with load()?

**Comment by jdalton** [comment]
It works for the [tests](https://github.com/jdalton/qunit-extras/blob/master/test/test.js) though I it may be version dependent.
