### ISSUE TITLE
assert.deepEqual throws TypeError when comparing Symbols

### ISSUE THREAD

**Issue by HarrySarson** [jdalton/qunit-extras#28]
When a comparison between arrays containing Symbols fails, rather than printing an error message the `assert.deepEqual` function throws a type error.

Failing code is:
```
QUnit.test('array of symbol comparision', assert => {
   assert.deepEqual([Symbol('aSymbol')], [5]); 
});
```

For a demo demonstrating the error please see: https://runkit.com/harrysarson/qunit-extras-symbols-bug.

I believe that somewhere `[Symbol('mySymbol')].toString()` is called which throws the error.

Interestingly the code fails in node v6.6 and v5.12 but not node v4.5.

**Comment by HarrySarson** [comment]
The offending line is: https://github.com/jdalton/qunit-extras/blob/master/qunit-extras.js#L470

The conversion using `String(expected)` fails if `expected` is `[Symbol('a')]`; an alternative would be to use the `util` library and as `util.inspect([Symbol('a')])` which would return `"[ Symbol(a) ]"`.

**Comment by jdalton** [comment]
@HarrySarson Thanks for digging into this!
