### ISSUE TITLE
qunitjs should be a dependancy rather than a devDependency

### ISSUE THREAD

**Issue by harrysarson** [jdalton/qunit-extras#29]
`$ npm install qunit-extras` does not install `qunitjs` as a dependency unless run with the `--dev` flag.

Without `qunitjs` installed the tests can't run in node, so `qunitjs` should be a normal dependency - not a devDependency.

When running `$ npm test` I get: `Error: Cannot find module 'qunitjs'`. Can be fixed by running `$npm install qunitjs` or adding it as a dependency of my project but it should come bundled.

**Comment by jdalton** [comment]
Hi @HarrySarson!

This is by design so folks can be in charge of which version of QUnit they include. `qunit-extras` is a companion package.
